spring:
  application:
    name: forohub
  config:
    import: optional:secrets.properties
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
server:
  error:
    include-stacktrace: never
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}
